import Lean4Lean.Theory.VDecl
import Lean4Lean.Theory.Typing.Basic

namespace Lean4Lean

deriving instance DecidableEq for VLevel
deriving instance DecidableEq for VExpr

/-- Syntactic underapproximation of `VLevel.IsNeverZero`,
mirroring `Lean.Level.isNeverZero`. -/
def VLevel.isNeverZero : VLevel → Bool
  | .zero | .param _ => false
  | .succ _ => true
  | .max l₁ l₂ => l₁.isNeverZero || l₂.isNeverZero
  | .imax _ l₂ => l₂.isNeverZero

instance VExpr.decClosedN : ∀ (e : VExpr) (k : Nat), Decidable (e.ClosedN k)
  | .bvar i, k => inferInstanceAs (Decidable (i < k))
  | .sort .., _ | .const .., _ => inferInstanceAs (Decidable True)
  | .app e1 e2, k => @instDecidableAnd _ _ (decClosedN e1 k) (decClosedN e2 k)
  | .lam e1 e2, k => @instDecidableAnd _ _ (decClosedN e1 k) (decClosedN e2 (k+1))
  | .forallE e1 e2, k => @instDecidableAnd _ _ (decClosedN e1 k) (decClosedN e2 (k+1))

instance VExpr.decLevelWF : ∀ (e : VExpr) (U : Nat), Decidable (e.LevelWF U)
  | .bvar _, _ => inferInstanceAs (Decidable True)
  | .sort l, U => VLevel.decidable_WF (n := U) (l := l)
  | .const _ ls, U => inferInstanceAs (Decidable (∀ l ∈ ls, l.WF U))
  | .app e1 e2, U | .lam e1 e2, U | .forallE e1 e2, U =>
    @instDecidableAnd _ _ (decLevelWF e1 U) (decLevelWF e2 U)

def VExpr.hasConst (n : Name) : VExpr → Bool
  | .bvar _ | .sort _ => false
  | .const c _ => c == n
  | .app e1 e2 | .lam e1 e2 | .forallE e1 e2 => e1.hasConst n || e2.hasConst n

def VExpr.appN (f : VExpr) : List VExpr → VExpr
  | [] => f
  | a :: as => (f.app a).appN as

/-- `[.bvar (off+m-1), ..., .bvar off]`: the spine referring to the last `m`
binders, skipping the innermost `off`. -/
def VExpr.bvarRevRange (off : Nat) : Nat → List VExpr
  | 0 => []
  | m+1 => .bvar (off + m) :: bvarRevRange off m

/-- Iterated lambda; the binder list is outermost first. -/
def VExpr.lamN : List VExpr → VExpr → VExpr
  | [], e => e
  | A :: As, e => .lam A (lamN As e)

/-- Iterated pi; the binder list is outermost first. -/
def VExpr.forallN : List VExpr → VExpr → VExpr
  | [], e => e
  | A :: As, e => .forallE A (forallN As e)

/-- Insert `n` binders below a telescope at depth `k`: the entry at depth
`j` within the telescope lifts by `n` at cutoff `k+j`. -/
def VExpr.liftTelN (n : Nat) : List VExpr → Nat → List VExpr
  | [], _ => []
  | A :: As, k => A.liftN n k :: liftTelN n As (k+1)

/-- The first `n` binder types of an iterated pi, outermost first. -/
def VExpr.telN : Nat → VExpr → List VExpr
  | 0, _ => []
  | n+1, .forallE A rest => A :: telN n rest
  | _+1, _ => []

/-- Strip `n` binders from an iterated pi. -/
def VExpr.dropN : Nat → VExpr → VExpr
  | 0, e => e
  | n+1, .forallE _ rest => dropN n rest
  | _+1, e => e

/-- The result of an iterated pi. -/
def VExpr.resultOf : VExpr → VExpr
  | .forallE _ rest => resultOf rest
  | e => e

/-- The application spine arguments, outermost first. -/
def VExpr.appArgs : VExpr → List VExpr → List VExpr
  | .app f a, acc => appArgs f (a :: acc)
  | _, acc => acc

def VExpr.appHead : VExpr → VExpr
  | .app f _ => appHead f
  | e => e

/-- The levels `[.param k, ..., .param (n+k-1)]`; `VLevel.params` shifted by `k`.
The recursor universe list is the elimination level (`.param 0`) followed by
the declaration's levels shifted by one, so declaration-world expressions
enter the recursor's universe context via `instL (params' n 1)`. -/
def VLevel.params' (n k : Nat) : List VLevel := (List.range n).map fun i => .param (i + k)

/-- Well-formedness of a binder telescope over a context. -/
def VEnv.OnTel (env : VEnv) (U : Nat) : List VExpr → List VExpr → Prop
  | _, [] => True
  | Γ, A :: As => env.IsType U Γ A ∧ OnTel env U (A :: Γ) As

/-- Pointwise definitional equality of two binder telescopes, checked in the
context generated by the left (raw) telescope. This is deliberately stronger
than whole-`forall` equality: it is the structural evidence a normalizer must
produce so mixed raw/view artifacts never need `forall` injectivity to recover
their binder alignment. -/
def VEnv.TelDefEq (env : VEnv) (U : Nat) :
    List VExpr → List VExpr → List VExpr → Prop
  | _, [], [] => True
  | Γ, A :: As, A' :: As' =>
    (∃ u, env.IsDefEq U Γ A A' (.sort u)) ∧
      TelDefEq env U (A :: Γ) As As'
  | _, _, _ => False

/-- Typing of an application spine against an iterated pi type: peeling the
expressions of `es` off `A` one instantiation at a time ends at `B`. This is
the pointwise typing evidence for index spines; `addInduct_WF` consumes it
wherever a recursive field or a constructor result applies the block to
index arguments. -/
def VEnv.SpineWF (env : VEnv) (U : Nat) (Γ : List VExpr) : VExpr → List VExpr → VExpr → Prop
  | A, [], B => A = B
  | A, e :: es, B => ∃ A₁ A₂, A = .forallE A₁ A₂ ∧ env.HasType U Γ e A₁ ∧
    SpineWF env U Γ (A₂.inst e) es B

namespace VInductDecl

variable (U : Nat) (T : Name) (np : Nat)

/-- The result sort of an inductive type past its parameters and
indices. -/
def sortLevel (ty : VInductiveType) : VLevel :=
  match VExpr.resultOf (VExpr.dropN np ty.type) with
  | .sort l => l
  | _ => .zero

/-- Constructor field types, outermost first. -/
def ctorFields : VExpr → List VExpr
  | .forallE B rest => B :: ctorFields rest
  | _ => []

/-- The block type applied to its parameters, seen from `off` binders past
the parameter telescope (declaration universes). -/
def recApp (off : Nat) : VExpr :=
  VExpr.appN (.const T (VLevel.params U)) (VExpr.bvarRevRange off np)

/-- Is `B` a direct recursive occurrence at field depth `j`: the block
constant applied to the parameter variables and `ni` block-free index
arguments. -/
def isRecField (ni j : Nat) (B : VExpr) : Bool :=
  VExpr.appHead B == .const T (VLevel.params U) &&
  (VExpr.appArgs B []).length == np + ni &&
  (VExpr.appArgs B []).take np == VExpr.bvarRevRange j np &&
  ((VExpr.appArgs B []).drop np).all fun e => !e.hasConst T

/-- The index arguments of a recursive occurrence (or of a constructor's
result). -/
def recFieldIdxs (B : VExpr) : List VExpr := (VExpr.appArgs B []).drop np

/-- One recursive constructor argument after normalization. `binders` is the
possibly empty Pi telescope leading to the recursive target. `fieldIndex`
addresses the constructor field itself, while target indices live under both
the preceding constructor fields and these binders. `targetType` is reserved
for the mutual-block index introduced by I3; it is zero in the current
one-family analyzer. -/
structure RecArg where
  fieldIndex : Nat
  binders : List VExpr
  targetType : Nat
  indices : List VExpr

/-- Recognize the kernel's one-family `isRecArg` shape in raw VExpr normal
form. Pi domains must be free of the family (the local strict-positivity
condition); the terminal target must be the family applied to the declaration
parameters and family-free indices. The returned telescope is outermost first.
-/
def recTarget? (ni : Nat) : Nat → VExpr → Option (List VExpr × List VExpr)
  | j, .forallE A rest =>
    if A.hasConst T then none
    else
      match recTarget? ni (j+1) rest with
      | some (As, idxs) => some (A :: As, idxs)
      | none => none
  | j, B =>
    if isRecField U T np ni j B then some ([], recFieldIdxs np B) else none

/-- Analyze a constructor field as a recursive argument, retaining its outer
field position and the complete binder telescope leading to the target. -/
def recArg? (ni j : Nat) (B : VExpr) : Option RecArg :=
  match recTarget? U T np ni j B with
  | some (binders, indices) =>
    some { fieldIndex := j, binders, targetType := 0, indices }
  | none => none

/-- Recursive arguments of a constructor field telescope, in field order. -/
def recArgs (ni : Nat) : List VExpr → (j : Nat := 0) → List RecArg
  | [], _ => []
  | B :: Bs, j =>
    match recArg? U T np ni j B with
    | some r => r :: recArgs ni Bs (j+1)
    | none => recArgs ni Bs (j+1)

/-- Positions of the directly recursive fields, with their index
arguments (`j` counts binders past the parameters). -/
def recPairs (ni : Nat) : List VExpr → (j : Nat := 0) → List (Nat × List VExpr)
  | [], _ => []
  | B :: Bs, j =>
    if isRecField U T np ni j B then (j, recFieldIdxs np B) :: recPairs ni Bs (j+1)
    else recPairs ni Bs (j+1)

/-- Induction-hypothesis binder types for the recursive positions with
their (recursor-universe) index arguments, at depth `p` past the `m`
field binders in context `params ++ [motive]`: the `p`-th is
`motive idxs xⱼ`, the index arguments shifted from field depth `j` (past
the parameters, no motive) into position. -/
def ihsFrom (m : Nat) : List (Nat × List VExpr) → Nat → List VExpr
  | [], _ => []
  | (j, idxs) :: rs, p =>
    VExpr.appN (.bvar (m+p))
      ((idxs.map fun e => (e.liftN 1 j).liftN (m-j+p)) ++ [.bvar (m-1-j+p)]) ::
    ihsFrom m rs (p+1)

/-- A stage-3 field is either an analyzed recursive argument (possibly under
a strictly-positive Pi telescope) or a type not mentioning the block at all.
The analyzer rejects family occurrences in recursive-Pi domains and indices.
-/
def stage3Field (ni j : Nat) (B : VExpr) : Bool :=
  (recArg? U T np ni j B).isSome || !B.hasConst T

/-- Stage-3 constructor type past the parameters: a telescope of stage-3
fields ending in the block's type constant applied to the parameters and
block-free index arguments. -/
def stage3Ctor (ni : Nat) : Nat → VExpr → Bool
  | j, .forallE B rest => stage3Field U T np ni j B && stage3Ctor ni (j+1) rest
  | j, e => isRecField U T np ni j e

/-- The kernel's subsingleton-elimination criterion, strengthened
syntactically: every non-recursive field appears literally among the
result's index arguments. -/
def subsingletonOK (ni : Nat) (ct : VExpr) : Bool :=
  let Bs := ctorFields ct
  let m := Bs.length
  let ridx := recFieldIdxs np (VExpr.resultOf ct)
  Bs.zipIdx.all fun (B, j) =>
    (recArg? U T np ni j B).isSome || ridx.contains (.bvar (m-1-j))

/-- Large elimination: a never-zero result sort, or the (syntactic)
subsingleton criterion. -/
def largeElim (ni : Nat) (ty : VInductiveType) : Bool :=
  (sortLevel np ty).isNeverZero ||
  match ty.ctors with
  | [] => true
  | [c] => subsingletonOK U T np ni (VExpr.dropN np c.type)
  | _ => false

/-- A family type is checked before its own constant is declared, so neither
its parameter nor index domains may already mention the family. This is the
one-family form of `checkInductiveTypes`' pre-environment type check. -/
def typeFormerOK (np : Nat) (ty : VInductiveType) : Bool :=
  (VExpr.telN np ty.type).all (fun e => !e.hasConst ty.name) &&
  (ctorFields (VExpr.dropN np ty.type)).all (fun e => !e.hasConst ty.name)

/-- The direct indexed recursion checks proved by the Stage-3 metatheory. -/
def stage3DirectCore (U np : Nat) (ty : VInductiveType) : Bool :=
  let ni := (ctorFields (VExpr.dropN np ty.type)).length
  ty.uvars == U &&
  (VExpr.telN np ty.type).length == np &&
  (match VExpr.resultOf (VExpr.dropN np ty.type) with
    | .sort l => decide (l.WF U)
    | _ => false) &&
  typeFormerOK np ty &&
  largeElim U ty.name np ni ty &&
  ty.ctors.all fun c => c.uvars == U &&
    VExpr.telN np c.type == VExpr.telN np ty.type &&
    stage3Ctor U ty.name np ni 0 (VExpr.dropN np c.type)

/-- Names reserved by a one-family transaction, in insertion order. -/
def generatedNames (ty : VInductiveType) : List Name :=
  ty.name :: (ty.ctors.map (fun c => c.name) ++ [.str ty.name "rec"])

/-- Internal duplicate/collision check, matching the sequential kernel name
reservations before any object becomes observable. -/
def namesOK (ty : VInductiveType) : Bool := decide (generatedNames ty).Nodup

/-- Kernel metadata types are closed before checking. Keeping this in the
computational descriptor prevents `addInduct` from accepting a hand-built
declaration with loose variables even when its result spine has the expected
head. -/
def closedOK (ty : VInductiveType) : Bool :=
  decide (ty.type.ClosedN 0) && ty.ctors.all fun c => decide (c.type.ClosedN 0)

/-- Every universe annotation in the family and constructor metadata must
refer to one of the declaration's universe parameters. The result-sort check
alone is insufficient: bad parameters or fields can hide an out-of-range
level while leaving the result universe valid. -/
def levelsOK (U : Nat) (ty : VInductiveType) : Bool :=
  decide (ty.type.LevelWF U) && ty.ctors.all fun c => decide (c.type.LevelWF U)

/-- The boolean core of the current one-family checker. Keeping this named
separately from `checked?` lets proofs unpack the accepted checks while all
consumers obtain their normalized data from the same descriptor. -/
def stage3Core : VInductDecl → Bool
  | ⟨U, np, [ty]⟩ =>
    stage3DirectCore U np ty && (namesOK ty && (closedOK ty && levelsOK U ty))
  | _ => false

/-- Constructor identities retained across normalization. Types may change by
WHNF/definitional equality, but names, universe arities, order, and count may
not. -/
def sameCtorHeaders : List VConstVal → List VConstVal → Bool
  | [], [] => true
  | c :: cs, c' :: cs' =>
    c.name == c'.name && c.uvars == c'.uvars && sameCtorHeaders cs cs'
  | _, _ => false

/-- Family identities retained across normalization. -/
def sameTypeHeaders : List VInductiveType → List VInductiveType → Bool
  | [], [] => true
  | ty :: tys, ty' :: tys' =>
    ty.name == ty'.name && ty.uvars == ty'.uvars &&
      sameCtorHeaders ty.ctors ty'.ctors && sameTypeHeaders tys tys'
  | _, _ => false

/-- Computational coherence between stored kernel metadata and a normalized
analysis view. Normalization may change expression payloads only; declaration
arity and every generated identity remain fixed. -/
def normalizationShape (source view : VInductDecl) : Bool :=
  source.uvars == view.uvars &&
    source.nparams == view.nparams &&
    sameTypeHeaders source.types view.types

/-- Constructor headers are reflexively coherent. Kept computational so the
identity normalization below reduces without an external oracle. -/
theorem sameCtorHeaders_refl : ∀ cs, sameCtorHeaders cs cs = true
  | [] => rfl
  | c :: cs => by
    change ((c.name == c.name) && (c.uvars == c.uvars) &&
      sameCtorHeaders cs cs) = true
    rw [beq_self_eq_true, beq_self_eq_true, sameCtorHeaders_refl]
    rfl

/-- Family headers are reflexively coherent. -/
theorem sameTypeHeaders_refl : ∀ tys, sameTypeHeaders tys tys = true
  | [] => rfl
  | ty :: tys => by
    change ((ty.name == ty.name) && (ty.uvars == ty.uvars) &&
      sameCtorHeaders ty.ctors ty.ctors && sameTypeHeaders tys tys) = true
    rw [beq_self_eq_true, beq_self_eq_true, sameCtorHeaders_refl,
      sameTypeHeaders_refl]
    rfl

theorem normalizationShape_refl (source : VInductDecl) :
    normalizationShape source source = true := by
  change ((source.uvars == source.uvars) &&
    (source.nparams == source.nparams) &&
    sameTypeHeaders source.types source.types) = true
  rw [beq_self_eq_true, beq_self_eq_true, sameTypeHeaders_refl]
  rfl

/-- A named, environment-independent normalization boundary. `source` is the
stored declaration whose constants must be added to the Theory environment;
`view` is the WHNF/defeq-normalized syntax inspected by the inductive
analyzer. The boolean coherence proof prevents normalization from changing
declaration identities or ordering. -/
structure Normalization (source : VInductDecl) where
  view : VInductDecl
  shape_eq : normalizationShape source view = true

/-- Construct a normalization boundary by computation. -/
def normalization? (source view : VInductDecl) : Option (Normalization source) :=
  if h : normalizationShape source view then some ⟨view, h⟩ else none

/-- Identity normalization is the compatibility path for declarations already
in the analyzer's raw VExpr normal form. -/
def Normalization.identity (source : VInductDecl) : Normalization source where
  view := source
  shape_eq := normalizationShape_refl source

/-- Semantic validity of a one-family normalization view. The family type is
definitionally equal in the input environment; constructor types are
definitionally equal after the raw family constant has been introduced, which
matches the staging of the kernel's inductive check. I3 will generalize the
single family insertion to a block insertion. -/
def Normalization.WF {source : VInductDecl} (norm : Normalization source)
    (env : VEnv) : Prop :=
  ∃ raw view,
    source.types = [raw] ∧ norm.view.types = [view] ∧
    env.IsDefEqU source.uvars [] raw.type view.type ∧
    ∀ envT, env.addConst raw.name raw.toVConstant = some envT →
      List.Forall₂
        (fun rawCtor viewCtor =>
          envT.IsDefEqU source.uvars [] rawCtor.type viewCtor.type)
        raw.ctors view.ctors

/-- Whether the recursor may eliminate into a fresh universe or is confined
to `Prop`. I2 will make the small case constructible; the current direct
indexed slice produces `large` descriptors only. -/
inductive ElimMode where
  | large
  | small
  deriving DecidableEq, Repr

/-- Normalized data for one constructor. -/
structure CheckedCtor where
  value : VConstVal
  fields : List VExpr
  recursive : List RecArg
  resultIndices : List VExpr

def CheckedCtor.ofDirect (U : Nat) (T : Name) (np ni : Nat)
    (c : VConstVal) : CheckedCtor where
  value := c
  fields := ctorFields (VExpr.dropN np c.type)
  recursive := recArgs U T np ni (ctorFields (VExpr.dropN np c.type))
  resultIndices := recFieldIdxs np (VExpr.resultOf (VExpr.dropN np c.type))

/-- Data-bearing result of the shared one-family analysis. The descriptor is
dependent on its source declaration, so it cannot silently describe a
different block. Its normalized fields are consumed by generation, proofs,
fixtures, and Verify alignment as I2 replaces the remaining duplicated
analysis. -/
structure Checked (source : VInductDecl) where
  type : VInductiveType
  types_eq : source.types = [type]
  params : List VExpr
  params_eq : params = VExpr.telN source.nparams type.type
  indices : List VExpr
  indices_eq : indices = ctorFields (VExpr.dropN source.nparams type.type)
  resultLevel : VLevel
  result_eq : VExpr.resultOf (VExpr.dropN source.nparams type.type) = .sort resultLevel
  elimination : ElimMode
  elimination_eq : elimination = .large
  names : List Name
  names_eq : names = generatedNames type
  constructors : List CheckedCtor
  constructors_eq : constructors = type.ctors.map
    (CheckedCtor.ofDirect source.uvars type.name source.nparams indices.length)
  accepted : stage3Core source = true

/-- Analyze the current direct-indexed class once and retain every normalized
component needed downstream. This is intentionally an `Option` rather than a
boolean so successful checking cannot discard the analysis it just computed. -/
def checked? : (decl : VInductDecl) → Option decl.Checked
  | ⟨U, np, [ty]⟩ =>
    match hresult : VExpr.resultOf (VExpr.dropN np ty.type) with
    | .sort l =>
      if h : stage3Core ⟨U, np, [ty]⟩ then
        let indices := ctorFields (VExpr.dropN np ty.type)
        some {
          type := ty
          types_eq := rfl
          params := VExpr.telN np ty.type
          params_eq := rfl
          indices
          indices_eq := rfl
          resultLevel := l
          result_eq := hresult
          elimination := .large
          elimination_eq := rfl
          names := generatedNames ty
          names_eq := rfl
          constructors := ty.ctors.map (CheckedCtor.ofDirect U ty.name np indices.length)
          constructors_eq := rfl
          accepted := h }
      else none
    | _ => none
  | _ => none

/-- A checked descriptor is proof-irrelevantly unique for its source
declaration. Every data field is fixed by the equations stored in `Checked`;
the remaining fields are propositions. -/
theorem Checked.unique {decl : VInductDecl}
    (a b : decl.Checked) : a = b := by
  have htype : a.type = b.type := by
    have hb := b.types_eq
    rw [a.types_eq] at hb
    injection hb
  have hparams : a.params = b.params := by
    rw [a.params_eq, b.params_eq, htype]
  have hindices : a.indices = b.indices := by
    rw [a.indices_eq, b.indices_eq, htype]
  have hlevel : a.resultLevel = b.resultLevel := by
    have hb := b.result_eq
    rw [← htype, a.result_eq] at hb
    injection hb
  have helim : a.elimination = b.elimination := by
    rw [a.elimination_eq, b.elimination_eq]
  have hnames : a.names = b.names := by
    rw [a.names_eq, b.names_eq, htype]
  have hctors : a.constructors = b.constructors := by
    rw [a.constructors_eq, b.constructors_eq, htype, hindices]
  cases a
  cases b
  simp_all

/-- Possessing a checked descriptor proves that the analyzer succeeds. This
is kept separate from uniqueness because reducing the dependent match in
`checked?` only needs its Boolean success result. -/
theorem Checked.analyzer_isSome {decl : VInductDecl}
    (checked : decl.Checked) : decl.checked?.isSome = true := by
  cases decl with
  | mk U np types =>
      rcases checked with
        ⟨type, types_eq, params, params_eq,
          indices, indices_eq, resultLevel, result_eq,
          elimination, elimination_eq, names, names_eq,
          constructors, constructors_eq, accepted⟩
      change types = [type] at types_eq
      subst types
      subst params
      subst indices
      subst elimination
      subst names
      subst constructors
      change (VExpr.dropN np type.type).resultOf =
        .sort resultLevel at result_eq
      simp only [VInductDecl.checked?]
      split <;> simp_all

/-- Every `Checked` value is the exact data-bearing result returned by the
analyzer. Consumers can therefore package an already-retained witness without
running or choosing a second analysis. -/
theorem Checked.analyzer_eq {decl : VInductDecl}
    (checked : decl.Checked) : decl.checked? = some checked := by
  cases h : decl.checked? with
  | none =>
      have his := checked.analyzer_isSome
      simp [h] at his
  | some actual =>
      exact congrArg some (actual.unique checked)

/-- The layout fragment of `stage3DirectCore` needed to pair an identity
normalization position-for-position. -/
theorem Checked.direct_layout {decl : VInductDecl}
    (checked : decl.Checked) :
    (VExpr.telN decl.nparams checked.type.type).length = decl.nparams ∧
      ∀ c ∈ checked.type.ctors,
        (VExpr.telN decl.nparams c.type).length = decl.nparams := by
  cases decl with
  | mk U np types =>
      have htypes : types = [checked.type] := checked.types_eq
      have hcore := checked.accepted
      simp only [stage3Core, htypes, Bool.and_eq_true] at hcore
      have hdirect := hcore.1
      simp only [stage3DirectCore, Bool.and_eq_true, beq_iff_eq,
        List.all_eq_true] at hdirect
      obtain ⟨⟨⟨⟨⟨-, hparams⟩, -⟩, -⟩, -⟩, hctors⟩ := hdirect
      refine ⟨hparams, fun c hc => ?_⟩
      rw [(hctors c hc).1.2]
      exact hparams

/-- Analyze an explicit normalized view without consulting the environment.
Semantic soundness is supplied separately by `Normalization.WF`; this split
matches the existing `Checked`/`Checked.WF` contract. -/
def Normalization.checked? {source : VInductDecl} (norm : Normalization source) :
    Option norm.view.Checked :=
  norm.view.checked?

/-- Acceptance of an explicit normalized view. -/
def Normalization.accepted {source : VInductDecl} (norm : Normalization source) : Bool :=
  norm.checked?.isSome

/-- One accepted raw/view pair. The raw declaration remains the index of this
object; every WHNF-sensitive decision is retained in the single checked view
that produced `checked_eq`. -/
structure NormalizedChecked (source : VInductDecl) where
  normalization : Normalization source
  sourceType : VInductiveType
  source_types_eq : source.types = [sourceType]
  checked : normalization.view.Checked
  checked_eq : normalization.checked? = some checked

/-- Analyze a normalization once and retain the exact dependent checked
descriptor that drove acceptance. -/
def Normalization.check? {source : VInductDecl} (norm : Normalization source) :
    Option (NormalizedChecked source) :=
  match hsource : source.types with
  | [sourceType] =>
    match hchecked : norm.checked? with
    | some checked => some ⟨norm, sourceType, hsource, checked, hchecked⟩
    | none => none
  | _ => none

/-- Construct and analyze a raw/view pair in one computational transaction. -/
def normalizedChecked? (source view : VInductDecl) : Option (NormalizedChecked source) := do
  let norm ← normalization? source view
  norm.check?

/-- Compatibility analyzer for metadata already accepted in raw syntax. -/
def identityChecked? (source : VInductDecl) : Option (NormalizedChecked source) :=
  (Normalization.identity source).check?

/-- Repackage an already-retained analyzer witness through the identity
normalization boundary. This is the compatibility block used by the public
`Checked` artifact accessors. -/
def Checked.identityBlock {decl : VInductDecl}
    (checked : decl.Checked) : NormalizedChecked decl where
  normalization := Normalization.identity decl
  sourceType := checked.type
  source_types_eq := checked.types_eq
  checked := checked
  checked_eq := checked.analyzer_eq

/-- One raw constructor paired, by position, with the checked descriptor from
the normalized view. The raw value owns kernel-observable binder syntax;
`view` owns WHNF-sensitive recursive classification and result indices. -/
structure NormalizedCtor where
  raw : VConstVal
  view : CheckedCtor

/-- Positional pairing used by the mixed artifact layer. A separate layout
check below rejects unequal list lengths instead of relying on `zip`'s
truncation behavior. -/
def pairNormalizedCtors : List VConstVal → List CheckedCtor → List NormalizedCtor
  | raw :: raws, view :: views =>
    ⟨raw, view⟩ :: pairNormalizedCtors raws views
  | _, _ => []

/-- Raw constructor fields, kept distinct from the normalized fields stored in
the checked view. -/
def NormalizedCtor.rawFields (ctor : NormalizedCtor) (np : Nat) : List VExpr :=
  ctorFields (VExpr.dropN np ctor.raw.type)

/-- All stored raw constructor binders, including the constructor's own
parameter prefix. -/
def NormalizedCtor.declaredBinders (ctor : NormalizedCtor) (np : Nat) :
    List VExpr :=
  VExpr.telN np ctor.raw.type ++ ctor.rawFields np

/-- The result retained in the stored raw constructor type. -/
def NormalizedCtor.rawResult (ctor : NormalizedCtor) (np : Nat) : VExpr :=
  VExpr.resultOf (VExpr.dropN np ctor.raw.type)

/-- The structural facts required before raw binders and normalized recursive
facts may drive one artifact. Semantic defeq remains the responsibility of
`Normalization.WF`; this Boolean only certifies positional layout. -/
def NormalizedCtor.generationShape (np : Nat) (ctor : NormalizedCtor) : Bool :=
  ctor.raw.name == ctor.view.value.name &&
    ctor.raw.uvars == ctor.view.value.uvars &&
    (VExpr.telN np ctor.raw.type).length == np &&
    (ctor.rawFields np).length == ctor.view.fields.length

def NormalizedChecked.rawParams {source : VInductDecl}
    (block : NormalizedChecked source) : List VExpr :=
  VExpr.telN source.nparams block.sourceType.type

def NormalizedChecked.rawIndices {source : VInductDecl}
    (block : NormalizedChecked source) : List VExpr :=
  ctorFields (VExpr.dropN source.nparams block.sourceType.type)

/-- The raw family result after its parameter and index binders. -/
def NormalizedChecked.rawResult {source : VInductDecl}
    (block : NormalizedChecked source) : VExpr :=
  VExpr.resultOf (VExpr.dropN source.nparams block.sourceType.type)

/-- Whether a stored parameter domain has one of the four top-level type
annotations consumed by Lean before it creates the common recursor parameter
telescope.  Ordinary reducible constants are intentionally not inspected:
their raw syntax remains observable in generated kernel metadata. -/
def _root_.Lean4Lean.VExpr.hasTypeAnnotation : VExpr → Bool
  | .app (.const name _) _ =>
    name == ``_root_.outParam || name == ``_root_.semiOutParam
  | .app (.app (.const name _) _) _ =>
    name == ``_root_.optParam || name == ``_root_.autoParam
  | _ => false

/-- Parameter surface emitted by recursor generation. Annotation wrappers use
the analyzer-owned consumed view; every other parameter keeps the stored raw
domain even when its WHNF differs. -/
def generationParam (raw view : VExpr) : VExpr :=
  if raw.hasTypeAnnotation then view else raw

/-- Positional common-parameter telescope used by generated artifacts. -/
def generationParams : List VExpr → List VExpr → List VExpr
  | raw :: raws, view :: views =>
    generationParam raw view :: generationParams raws views
  | _, _ => []

@[simp] theorem generationParams_self :
    ∀ params, generationParams params params = params
  | [] => rfl
  | param :: params => by
    simp [generationParams, generationParam, generationParams_self params]

theorem generationParams_length_of_eq :
    ∀ {raw view : List VExpr}, raw.length = view.length →
      (generationParams raw view).length = raw.length
  | [], [], _ => rfl
  | _ :: _, _ :: _, h => by
    simp only [generationParams, List.length_cons]
    exact congrArg Nat.succ
      (generationParams_length_of_eq (Nat.succ.inj h))

def NormalizedChecked.generationParams {source : VInductDecl}
    (block : NormalizedChecked source) : List VExpr :=
  VInductDecl.generationParams block.rawParams block.checked.params

def NormalizedChecked.ctorPairs {source : VInductDecl}
    (block : NormalizedChecked source) : List NormalizedCtor :=
  pairNormalizedCtors block.sourceType.ctors block.checked.constructors

/-- Executable layout gate for mixed raw/view generation. It proves that every
raw binder position has exactly one normalized analysis position without
claiming that their expression payloads are syntactically equal. -/
def NormalizedChecked.generationShape {source : VInductDecl}
    (block : NormalizedChecked source) : Bool :=
  block.rawParams.length == source.nparams &&
    block.rawParams.length == block.checked.params.length &&
    block.rawIndices.length == block.checked.indices.length &&
    block.ctorPairs.length == block.sourceType.ctors.length &&
    block.ctorPairs.length == block.checked.constructors.length &&
    block.ctorPairs.all (NormalizedCtor.generationShape source.nparams)

/-- Pairing a constructor list with its direct checked analysis preserves its
length and satisfies every per-constructor identity-layout check. -/
theorem pairNormalizedCtors_ofDirect_generationShape
    (U : Nat) (T : Name) (np ni : Nat) :
    ∀ (cs : List VConstVal),
      (∀ c ∈ cs, (VExpr.telN np c.type).length = np) →
      let pairs := pairNormalizedCtors cs
        (cs.map (CheckedCtor.ofDirect U T np ni))
      pairs.length = cs.length ∧
        pairs.all (NormalizedCtor.generationShape np) = true
  | [], _ => by simp [pairNormalizedCtors]
  | c :: cs, h => by
      have hc := h c (.head _)
      have hcs : ∀ c ∈ cs, (VExpr.telN np c.type).length = np :=
        fun c hc => h c (.tail _ hc)
      have ih := pairNormalizedCtors_ofDirect_generationShape
        U T np ni cs hcs
      simp [pairNormalizedCtors, NormalizedCtor.generationShape,
        CheckedCtor.ofDirect, NormalizedCtor.rawFields, hc, ih]

/-- A normalized checked block whose raw outer telescopes are positionally
usable by artifact generation. This is still analysis data, not semantic
normalization evidence; preservation additionally requires
`NormalizedChecked.WF`. -/
structure GenerationChecked (source : VInductDecl) where
  block : NormalizedChecked source
  shape_eq : block.generationShape = true

/-- Identity normalization always satisfies the mixed generator's positional
layout gate. The only non-reflexive facts are the parameter and constructor
parameter lengths already certified by Stage 3. -/
theorem Checked.identityBlock_generationShape {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityBlock.generationShape = true := by
  have hp : (VExpr.telN decl.nparams checked.type.type).length =
      decl.nparams := checked.direct_layout.1
  have hcs : ∀ c ∈ checked.type.ctors,
      (VExpr.telN decl.nparams c.type).length = decl.nparams :=
    checked.direct_layout.2
  have hpairs := pairNormalizedCtors_ofDirect_generationShape
    decl.uvars checked.type.name decl.nparams checked.indices.length
    checked.type.ctors hcs
  simp only [NormalizedChecked.generationShape, Bool.and_eq_true,
    beq_iff_eq, Checked.identityBlock, NormalizedChecked.rawParams,
    NormalizedChecked.rawIndices, NormalizedChecked.ctorPairs]
  rw [checked.params_eq, checked.indices_eq, checked.constructors_eq]
  simp only [List.length_map]
  exact ⟨⟨⟨⟨⟨hp, trivial⟩, trivial⟩, hpairs.1⟩,
    hpairs.1⟩, hpairs.2⟩

/-- Canonical mixed-generation witness for a declaration already accepted in
raw analyzer normal form. -/
def Checked.identityGeneration {decl : VInductDecl}
    (checked : decl.Checked) : GenerationChecked decl where
  block := checked.identityBlock
  shape_eq := checked.identityBlock_generationShape

@[simp] theorem Checked.identityGeneration_sourceType
    {decl : VInductDecl} (checked : decl.Checked) :
    checked.identityGeneration.block.sourceType = checked.type := rfl

@[simp] theorem Checked.identityGeneration_checked
    {decl : VInductDecl} (checked : decl.Checked) :
    checked.identityGeneration.block.checked = checked := rfl

def NormalizedChecked.generation? {source : VInductDecl}
    (block : NormalizedChecked source) : Option (GenerationChecked source) :=
  if h : block.generationShape then some ⟨block, h⟩ else none

def Normalization.generation? {source : VInductDecl}
    (norm : Normalization source) : Option (GenerationChecked source) := do
  let block ← norm.check?
  block.generation?

def normalizedGeneration? (source view : VInductDecl) :
    Option (GenerationChecked source) := do
  let block ← normalizedChecked? source view
  block.generation?

def identityGeneration? (source : VInductDecl) :
    Option (GenerationChecked source) := do
  let block ← identityChecked? source
  block.generation?

/-- The public acceptance predicate is the existence of a checked descriptor,
not a second ad-hoc pass over the declaration. -/
def stage3 (decl : VInductDecl) : Bool := decl.checked?.isSome

/-- The parameter telescope in the recursor's universe context. -/
def paramsTel (ty : VInductiveType) : List VExpr :=
  (VExpr.telN np ty.type).map (VExpr.instL (VLevel.params' U 1))

/-- The index telescope in the recursor's universe context (at parameter
depth). -/
def idxTel (ty : VInductiveType) : List VExpr :=
  (ctorFields (VExpr.dropN np ty.type)).map (VExpr.instL (VLevel.params' U 1))

/-- `recApp` in the recursor's universe context. -/
def recApp' (off : Nat) : VExpr :=
  VExpr.appN (.const T (VLevel.params' U 1)) (VExpr.bvarRevRange off np)

/-- `motive : ∀ indices, T params indices → Sort u`, in context
`params`. -/
def motiveType (ty : VInductiveType) : VExpr :=
  let ni := (idxTel U np ty).length
  VExpr.forallN (idxTel U np ty)
    (.forallE (VExpr.appN (.const T (VLevel.params' U 1))
      (VExpr.bvarRevRange ni np ++ VExpr.bvarRevRange 0 ni))
      (.sort (.param 0)))

/-- Constructor fields in the recursor's universe context (still at
parameter depth, no motive shift). -/
def ctorFieldsR (c : VConstVal) : List VExpr :=
  (ctorFields (VExpr.dropN np c.type)).map (VExpr.instL (VLevel.params' U 1))

/-- The recursive positions of a constructor with their index arguments,
in the recursor's universe context. -/
def recPairsR (ni : Nat) (c : VConstVal) : List (Nat × List VExpr) :=
  (recPairs U T np ni (ctorFields (VExpr.dropN np c.type))).map
    fun (j, idxs) => (j, idxs.map (VExpr.instL (VLevel.params' U 1)))

/-- A recursive-argument descriptor transported into the recursor's universe
context. Telescope dependency is preserved because universe instantiation does
not change term-variable indices. -/
def RecArg.instL (r : RecArg) (ls : List VLevel) : RecArg where
  fieldIndex := r.fieldIndex
  binders := r.binders.map (VExpr.instL ls)
  targetType := r.targetType
  indices := r.indices.map (VExpr.instL ls)

/-- Recursive constructor arguments, including recursive Pi arguments, in the
recursor universe context. -/
def recArgsR (ni : Nat) (c : VConstVal) : List RecArg :=
  (recArgs U T np ni (ctorFields (VExpr.dropN np c.type))).map
    fun r => r.instL (VLevel.params' U 1)

/-- The result index arguments of a constructor, recursor universes (at
result depth: past the parameters and all fields, no motive). -/
def ctorIdxs (c : VConstVal) : List VExpr :=
  (recFieldIdxs np (VExpr.resultOf (VExpr.dropN np c.type))).map
    (VExpr.instL (VLevel.params' U 1))

/-- The minor premise for one constructor, in context `params ++ [motive]`:
`∀ fields, ∀ ihs, motive idxs (ctor params fields)`, with one induction
hypothesis per directly recursive field. The fields shift by one for the
interposed motive. -/
def minorType (ty : VInductiveType) (c : VConstVal) : VExpr :=
  let Bs := ctorFieldsR U np c
  let m := Bs.length
  let ni := (idxTel U np ty).length
  let rsP := recPairsR U T np ni c
  let r := rsP.length
  VExpr.forallN (VExpr.liftTelN 1 Bs 0)
    (VExpr.forallN (ihsFrom m rsP 0)
      (VExpr.appN (.bvar (m+r))
        (((ctorIdxs U np c).map fun e => (e.liftN 1 m).liftN r) ++
          [VExpr.appN (.const c.name (VLevel.params' U 1))
            (VExpr.bvarRevRange (r+m+1) np ++ VExpr.bvarRevRange r m)])))

/-- Binder telescope of a functional induction hypothesis. Starting from the
recursive argument's own telescope, insert the motive below the preceding
constructor fields, then insert the current/later fields and earlier induction
hypotheses above them. -/
def RecArg.minorBinders (m p : Nat) (r : RecArg) : List VExpr :=
  VExpr.liftTelN (m - r.fieldIndex + p)
    (VExpr.liftTelN 1 r.binders r.fieldIndex) 0

/-- The induction-hypothesis type generated for one recursive argument. For a
direct recursive field this reduces to `motive indices field`; under a Pi it
is `∀ xs, motive indices (field xs)`. -/
def RecArg.minorIH (m p : Nat) (r : RecArg) : VExpr :=
  let n := r.binders.length
  VExpr.forallN (r.minorBinders m p)
    (VExpr.appN (.bvar (m+p+n))
      ((r.indices.map fun e =>
          (e.liftN 1 (r.fieldIndex+n)).liftN (m-r.fieldIndex+p) n) ++
        [VExpr.appN (.bvar (m-1-r.fieldIndex+p+n))
          (VExpr.bvarRevRange 0 n)]))

/-- Functional induction-hypothesis telescope, one entry per recursive
constructor argument. -/
def ihsFromRecArgs (m : Nat) : List RecArg → Nat → List VExpr
  | [], _ => []
  | r :: rs, p => r.minorIH m p :: ihsFromRecArgs m rs (p+1)

/-- General one-family minor premise, extending `minorType` to recursive
arguments beneath Pi telescopes. -/
def minorTypeRec (ty : VInductiveType) (c : VConstVal) : VExpr :=
  let Bs := ctorFieldsR U np c
  let m := Bs.length
  let ni := (idxTel U np ty).length
  let rs := recArgsR U T np ni c
  let r := rs.length
  VExpr.forallN (VExpr.liftTelN 1 Bs 0)
    (VExpr.forallN (ihsFromRecArgs m rs 0)
      (VExpr.appN (.bvar (m+r))
        (((ctorIdxs U np c).map fun e => (e.liftN 1 m).liftN r) ++
          [VExpr.appN (.const c.name (VLevel.params' U 1))
            (VExpr.bvarRevRange (r+m+1) np ++ VExpr.bvarRevRange r m)])))

def minorTypesRec (ty : VInductiveType) : List VConstVal → (i : Nat := 0) → List VExpr
  | [], _ => []
  | c :: cs, i => VExpr.liftN i (minorTypeRec U T np ty c) :: minorTypesRec ty cs (i+1)

def recTypeRec (ty : VInductiveType) : VExpr :=
  let k := ty.ctors.length
  let ni := (idxTel U np ty).length
  VExpr.forallN (paramsTel U np ty) <|
    .forallE (motiveType U T np ty) <|
      VExpr.forallN (minorTypesRec U T np ty ty.ctors) <|
        VExpr.forallN (VExpr.liftTelN (k+1) (idxTel U np ty) 0) <|
          .forallE (VExpr.appN (.const T (VLevel.params' U 1))
            (VExpr.bvarRevRange (ni+k+1) np ++ VExpr.bvarRevRange 0 ni)) <|
            .app (VExpr.appN (.bvar (ni+k+1)) (VExpr.bvarRevRange 1 ni)) (.bvar 0)

def recConstRec (ty : VInductiveType) : VConstant := ⟨U + 1, recTypeRec U T np ty⟩

/-- The telescope introduced around a functional recursive call in an iota
RHS. It is the source Pi telescope transported under the recursor's common
arguments and the complete constructor-field context. -/
def RecArg.ruleBinders (m k : Nat) (r : RecArg) : List VExpr :=
  VExpr.liftTelN (m-r.fieldIndex)
    (VExpr.liftTelN (k+1) r.binders r.fieldIndex) 0

/-- Recursive call contributed to an iota RHS. Direct recursion reduces to a
plain call; a recursive Pi argument produces a lambda applying the field to
the freshly bound arguments before recurring. -/
def RecArg.ruleCall (m k : Nat) (recBase : VExpr) (r : RecArg) : VExpr :=
  let n := r.binders.length
  VExpr.lamN (r.ruleBinders m k)
    (VExpr.appN (recBase.liftN n)
      ((r.indices.map fun e =>
          (e.liftN (k+1) (r.fieldIndex+n)).liftN (m-r.fieldIndex) n) ++
        [VExpr.appN (.bvar (m-1-r.fieldIndex+n))
          (VExpr.bvarRevRange 0 n)]))

/-- The functional-IH type expected of `ruleCall` in the complete iota-rule
context. Keeping this normalization named makes the preservation proof and
the generated RHS share one de Bruijn convention. -/
def RecArg.ruleIH (m k : Nat) (r : RecArg) : VExpr :=
  let n := r.binders.length
  VExpr.forallN (r.ruleBinders m k)
    (VExpr.appN (.bvar (k+m+n))
      ((r.indices.map fun e =>
          (e.liftN (k+1) (r.fieldIndex+n)).liftN (m-r.fieldIndex) n) ++
        [VExpr.appN (.bvar (m-1-r.fieldIndex+n))
          (VExpr.bvarRevRange 0 n)]))

/-- Functional-IH telescope in an iota-rule context. Each entry is weakened
past the preceding IH binders, while its base type is exactly `ruleIH`. -/
def ruleIHs (m k : Nat) : List RecArg → Nat → List VExpr
  | [], _ => []
  | r :: rs, p => (r.ruleIH m k).liftN p :: ruleIHs m k rs (p+1)

def ruleRec (ty : VInductiveType) (i : Nat) (c : VConstVal) : VDefEq :=
  let k := ty.ctors.length
  let Bs := ctorFieldsR U np c
  let m := Bs.length
  let ni := (idxTel U np ty).length
  let rs := recArgsR U T np ni c
  let binders := paramsTel U np ty ++
    motiveType U T np ty :: minorTypesRec U T np ty ty.ctors ++
    VExpr.liftTelN (k+1) Bs 0
  let recBase := VExpr.appN (.const (.str T "rec") (VLevel.params (U+1)))
    (VExpr.bvarRevRange m (np+k+1))
  let idxR := (ctorIdxs U np c).map fun e => e.liftN (k+1) m
  let ctorApp := VExpr.appN (.const c.name (VLevel.params' U 1))
    (VExpr.bvarRevRange (m+k+1) np ++ VExpr.bvarRevRange 0 m)
  let ihs := rs.map fun r => r.ruleCall m k recBase
  { uvars := U + 1
    lhs := VExpr.lamN binders (VExpr.appN recBase (idxR ++ [ctorApp]))
    rhs := VExpr.lamN binders
      (VExpr.appN (.bvar (k-1-i+m)) (VExpr.bvarRevRange 0 m ++ ihs))
    type := VExpr.forallN binders (VExpr.appN (.bvar (k+m)) (idxR ++ [ctorApp])) }

def rulesRec (ty : VInductiveType) : List VDefEq :=
  ty.ctors.zipIdx.map fun (c, i) => ruleRec U T np ty i c

/-- Minor premise types in position: the `i`-th lives under
`params ++ motive` and the previous `i` minors. -/
def minorTypes (ty : VInductiveType) : List VConstVal → (i : Nat := 0) → List VExpr
  | [], _ => []
  | c :: cs, i => VExpr.liftN i (minorType U T np ty c) :: minorTypes ty cs (i+1)

/-- The recursor type `∀ params, ∀ (motive : ∀ indices, T params indices →
Sort u) (minors..) (indices..) (t : T params indices), motive indices t`. -/
def recType (ty : VInductiveType) : VExpr :=
  let k := ty.ctors.length
  let ni := (idxTel U np ty).length
  VExpr.forallN (paramsTel U np ty) <|
    .forallE (motiveType U T np ty) <|
      VExpr.forallN (minorTypes U T np ty ty.ctors) <|
        VExpr.forallN (VExpr.liftTelN (k+1) (idxTel U np ty) 0) <|
          .forallE (VExpr.appN (.const T (VLevel.params' U 1))
            (VExpr.bvarRevRange (ni+k+1) np ++ VExpr.bvarRevRange 0 ni)) <|
            .app (VExpr.appN (.bvar (ni+k+1)) (VExpr.bvarRevRange 1 ni)) (.bvar 0)

def recConst (ty : VInductiveType) : VConstant := ⟨U + 1, recType U T np ty⟩

/-- The iota rule for the `i`-th constructor, as a closed defeq between
lambda telescopes over `params ++ motive :: minors ++ fields` (the same
shape as `quotDefEq`, and the same telescope the kernel's
`RecursorRule.rhs` binds). The left body is the `SimplePattern.iota`
spine: the recursor applied to the parameters, motive, minors and the
constructor's result indices, with a constructor-headed major. -/
def rule (ty : VInductiveType) (i : Nat) (c : VConstVal) : VDefEq :=
  let k := ty.ctors.length
  let Bs := ctorFieldsR U np c
  let m := Bs.length
  let ni := (idxTel U np ty).length
  let rsP := recPairsR U T np ni c
  let binders := paramsTel U np ty ++
    motiveType U T np ty :: minorTypes U T np ty ty.ctors ++
    VExpr.liftTelN (k+1) Bs 0
  let recBase := VExpr.appN (.const (.str T "rec") (VLevel.params (U+1)))
    (VExpr.bvarRevRange m (np+k+1))
  let idxR := (ctorIdxs U np c).map fun e => e.liftN (k+1) m
  let ctorApp := VExpr.appN (.const c.name (VLevel.params' U 1))
    (VExpr.bvarRevRange (m+k+1) np ++ VExpr.bvarRevRange 0 m)
  let ihs := rsP.map fun (j, idxs) =>
    VExpr.appN recBase
      ((idxs.map fun e => (e.liftN (k+1) j).liftN (m-j)) ++ [.bvar (m-1-j)])
  { uvars := U + 1
    lhs := VExpr.lamN binders (VExpr.appN recBase (idxR ++ [ctorApp]))
    rhs := VExpr.lamN binders
      (VExpr.appN (.bvar (k-1-i+m)) (VExpr.bvarRevRange 0 m ++ ihs))
    type := VExpr.forallN binders (VExpr.appN (.bvar (k+m)) (idxR ++ [ctorApp])) }

def rules (ty : VInductiveType) : List VDefEq :=
  ty.ctors.zipIdx.map fun (c, i) => rule U T np ty i c

namespace NormalizedCtor

/-- Raw field binders transported to the recursor universe context. -/
def fieldsR (ctor : NormalizedCtor) (U np : Nat) : List VExpr :=
  (ctor.rawFields np).map (VExpr.instL (VLevel.params' U 1))

/-- Normalized recursive classifications transported without re-peeling the
raw constructor type. -/
def recArgsR (ctor : NormalizedCtor) (U : Nat) : List RecArg :=
  ctor.view.recursive.map fun r => r.instL (VLevel.params' U 1)

/-- Normalized constructor-result indices in recursor universes. -/
def resultIndicesR (ctor : NormalizedCtor) (U : Nat) : List VExpr :=
  ctor.view.resultIndices.map (VExpr.instL (VLevel.params' U 1))

end NormalizedCtor

/-! ## Mixed raw/view artifacts

These definitions are additive until their preservation theorem is complete.
Raw family/constructor telescopes supply emitted binder syntax; the checked
view supplies result indices and recursive-argument classification. No helper
below re-runs `recArg?` on raw metadata.
-/

namespace GenerationChecked

/-- Kernel-observable family-parameter telescope in recursor universes.

Lean consumes the four parameter annotations before emission, but otherwise
retains stored syntax rather than replacing reducible aliases by their WHNF. -/
def paramsTel {source : VInductDecl} (gen : GenerationChecked source) :
    List VExpr :=
  gen.block.generationParams.map
    (VExpr.instL (VLevel.params' source.uvars 1))

/-- Raw index-binder telescope in recursor universes. -/
def idxTel {source : VInductDecl} (gen : GenerationChecked source) :
    List VExpr :=
  gen.block.rawIndices.map (VExpr.instL (VLevel.params' source.uvars 1))

/-- Mixed motive: raw index binders, normalized index arity, and the retained
raw family identity. -/
def motiveType {source : VInductDecl} (gen : GenerationChecked source) : VExpr :=
  let ni := gen.idxTel.length
  VExpr.forallN gen.idxTel
    (.forallE
      (VExpr.appN
        (.const gen.block.sourceType.name (VLevel.params' source.uvars 1))
        (VExpr.bvarRevRange ni source.nparams ++ VExpr.bvarRevRange 0 ni))
      (.sort (.param 0)))

/-- One mixed minor premise. Raw fields are bound verbatim, while induction
hypotheses and constructor result indices come from the checked view. -/
def minorType {source : VInductDecl} (ctor : NormalizedCtor) : VExpr :=
  let Bs := ctor.fieldsR source.uvars source.nparams
  let m := Bs.length
  let rs := ctor.recArgsR source.uvars
  let r := rs.length
  VExpr.forallN (VExpr.liftTelN 1 Bs 0)
    (VExpr.forallN (ihsFromRecArgs m rs 0)
      (VExpr.appN (.bvar (m+r))
        ((ctor.resultIndicesR source.uvars |>.map fun e =>
            (e.liftN 1 m).liftN r) ++
          [VExpr.appN
            (.const ctor.raw.name (VLevel.params' source.uvars 1))
            (VExpr.bvarRevRange (r+m+1) source.nparams ++
              VExpr.bvarRevRange r m)])))

def minorTypesAux {source : VInductDecl} (gen : GenerationChecked source) :
    List NormalizedCtor → (i : Nat := 0) → List VExpr
  | [], _ => []
  | ctor :: ctors, i =>
    VExpr.liftN i (minorType (source := source) ctor) ::
      gen.minorTypesAux ctors (i+1)

def minorTypes {source : VInductDecl} (gen : GenerationChecked source) :
    List VExpr :=
  gen.minorTypesAux gen.block.ctorPairs

/-- Mixed recursor type. Its binder surface is raw, but every
WHNF-sensitive choice was retained by the checked view. -/
def recType {source : VInductDecl} (gen : GenerationChecked source) : VExpr :=
  let k := gen.block.ctorPairs.length
  let ni := gen.idxTel.length
  VExpr.forallN gen.paramsTel <|
    .forallE gen.motiveType <|
      VExpr.forallN gen.minorTypes <|
        VExpr.forallN (VExpr.liftTelN (k+1) gen.idxTel 0) <|
          .forallE
            (VExpr.appN
              (.const gen.block.sourceType.name
                (VLevel.params' source.uvars 1))
              (VExpr.bvarRevRange (ni+k+1) source.nparams ++
                VExpr.bvarRevRange 0 ni)) <|
            .app
              (VExpr.appN (.bvar (ni+k+1)) (VExpr.bvarRevRange 1 ni))
              (.bvar 0)

def recursor {source : VInductDecl} (gen : GenerationChecked source) :
    VConstant :=
  ⟨source.uvars + 1, gen.recType⟩

/-- One mixed iota rule. Raw fields and constructor names are observable in
the rule telescope; normalized recursive descriptors determine recursive calls
and normalized result indices determine the major's index spine. -/
def rule {source : VInductDecl} (gen : GenerationChecked source)
    (i : Nat) (ctor : NormalizedCtor) : VDefEq :=
  let k := gen.block.ctorPairs.length
  let Bs := ctor.fieldsR source.uvars source.nparams
  let m := Bs.length
  let rs := ctor.recArgsR source.uvars
  let binders := gen.paramsTel ++
    gen.motiveType :: gen.minorTypes ++
    VExpr.liftTelN (k+1) Bs 0
  let recBase := VExpr.appN
    (.const (.str gen.block.sourceType.name "rec")
      (VLevel.params (source.uvars+1)))
    (VExpr.bvarRevRange m (source.nparams+k+1))
  let idxR := ctor.resultIndicesR source.uvars |>.map fun e =>
    e.liftN (k+1) m
  let ctorApp := VExpr.appN
    (.const ctor.raw.name (VLevel.params' source.uvars 1))
    (VExpr.bvarRevRange (m+k+1) source.nparams ++
      VExpr.bvarRevRange 0 m)
  let ihs := rs.map fun r => r.ruleCall m k recBase
  { uvars := source.uvars + 1
    lhs := VExpr.lamN binders (VExpr.appN recBase (idxR ++ [ctorApp]))
    rhs := VExpr.lamN binders
      (VExpr.appN (.bvar (k-1-i+m)) (VExpr.bvarRevRange 0 m ++ ihs))
    type := VExpr.forallN binders
      (VExpr.appN (.bvar (k+m)) (idxR ++ [ctorApp])) }

def generatedRules {source : VInductDecl} (gen : GenerationChecked source) :
    List VDefEq :=
  gen.block.ctorPairs.zipIdx.map fun (ctor, i) => gen.rule i ctor

end GenerationChecked

namespace Checked

private theorem identity_paramsTel {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.paramsTel =
      VInductDecl.paramsTel decl.uvars decl.nparams checked.type := by
  simp [GenerationChecked.paramsTel, VInductDecl.paramsTel,
    NormalizedChecked.generationParams, NormalizedChecked.rawParams,
    Checked.identityGeneration, Checked.identityBlock, checked.params_eq]

private theorem identity_idxTel {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.idxTel =
      VInductDecl.idxTel decl.uvars decl.nparams checked.type := rfl

private theorem identity_motiveType {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.motiveType =
      VInductDecl.motiveType decl.uvars checked.type.name decl.nparams
        checked.type := rfl

private theorem identity_minorType {decl : VInductDecl}
    (checked : decl.Checked) (c : VConstVal) :
    GenerationChecked.minorType (source := decl)
      ⟨c, CheckedCtor.ofDirect decl.uvars checked.type.name decl.nparams
        checked.indices.length c⟩ =
      VInductDecl.minorTypeRec decl.uvars checked.type.name decl.nparams
        checked.type c := by
  have hni : checked.indices.length =
      (VInductDecl.idxTel decl.uvars decl.nparams checked.type).length := by
    rw [checked.indices_eq]
    simp [VInductDecl.idxTel]
  rw [hni]
  rfl

private theorem identity_minorTypesAux {decl : VInductDecl}
    (checked : decl.Checked) :
    ∀ (cs : List VConstVal) (i : Nat),
      checked.identityGeneration.minorTypesAux
        (pairNormalizedCtors cs
          (cs.map (CheckedCtor.ofDirect decl.uvars checked.type.name
            decl.nparams checked.indices.length))) i =
      VInductDecl.minorTypesRec decl.uvars checked.type.name decl.nparams
        checked.type cs i
  | [], _ => rfl
  | c :: cs, i => by
      simp [pairNormalizedCtors, GenerationChecked.minorTypesAux,
        VInductDecl.minorTypesRec, identity_minorType,
        identity_minorTypesAux checked cs (i+1)]

private theorem identity_minorTypes {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.minorTypes =
      VInductDecl.minorTypesRec decl.uvars checked.type.name decl.nparams
        checked.type checked.type.ctors := by
  unfold GenerationChecked.minorTypes
  simp only [Checked.identityGeneration, Checked.identityBlock,
    NormalizedChecked.ctorPairs]
  rw [checked.constructors_eq]
  exact identity_minorTypesAux checked checked.type.ctors 0

private theorem identity_recType {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.recType =
      VInductDecl.recTypeRec decl.uvars checked.type.name decl.nparams
        checked.type := by
  simp only [GenerationChecked.recType, VInductDecl.recTypeRec]
  rw [identity_paramsTel checked, identity_motiveType checked,
    identity_minorTypes checked, identity_idxTel checked]
  simp only [Checked.identityGeneration, Checked.identityBlock,
    NormalizedChecked.ctorPairs]
  rw [checked.constructors_eq,
    pairNormalizedCtors_ofDirect_generationShape
      decl.uvars checked.type.name decl.nparams checked.indices.length
      checked.type.ctors checked.direct_layout.2 |>.1]

private theorem identity_recursor {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.recursor =
      VInductDecl.recConstRec decl.uvars checked.type.name decl.nparams
        checked.type := by
  unfold GenerationChecked.recursor VInductDecl.recConstRec
  rw [identity_recType checked]

private theorem identity_rule {decl : VInductDecl}
    (checked : decl.Checked) (i : Nat) (c : VConstVal) :
    checked.identityGeneration.rule i
        ⟨c, CheckedCtor.ofDirect decl.uvars checked.type.name decl.nparams
          checked.indices.length c⟩ =
      VInductDecl.ruleRec decl.uvars checked.type.name decl.nparams
        checked.type i c := by
  have hni : checked.indices.length =
      (VInductDecl.idxTel decl.uvars decl.nparams checked.type).length := by
    rw [checked.indices_eq]
    simp [VInductDecl.idxTel]
  have hk : checked.identityGeneration.block.ctorPairs.length =
      checked.type.ctors.length := by
    simp only [Checked.identityGeneration, Checked.identityBlock,
      NormalizedChecked.ctorPairs]
    rw [checked.constructors_eq]
    exact (pairNormalizedCtors_ofDirect_generationShape
      decl.uvars checked.type.name decl.nparams checked.indices.length
      checked.type.ctors checked.direct_layout.2).1
  unfold GenerationChecked.rule VInductDecl.ruleRec
  rw [identity_paramsTel checked, identity_motiveType checked,
    identity_minorTypes checked, hk, hni]
  rfl

private theorem identity_rulesAux {decl : VInductDecl}
    (checked : decl.Checked) :
    ∀ (cs : List VConstVal) (n : Nat),
      List.map
        (fun (ctor, i) => checked.identityGeneration.rule i ctor)
        (List.zipIdx
          (pairNormalizedCtors cs
            (cs.map (CheckedCtor.ofDirect decl.uvars checked.type.name
              decl.nparams checked.indices.length))) n) =
      List.map
        (fun (c, i) =>
          VInductDecl.ruleRec decl.uvars checked.type.name decl.nparams
            checked.type i c)
        (List.zipIdx cs n)
  | [], _ => rfl
  | c :: cs, n => by
      simp [pairNormalizedCtors, List.zipIdx, identity_rule,
        identity_rulesAux checked cs (n+1)]

private theorem identity_generatedRules {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.identityGeneration.generatedRules =
      VInductDecl.rulesRec decl.uvars checked.type.name decl.nparams
        checked.type := by
  unfold GenerationChecked.generatedRules VInductDecl.rulesRec
  simp only [Checked.identityGeneration, Checked.identityBlock,
    NormalizedChecked.ctorPairs]
  rw [checked.constructors_eq]
  exact identity_rulesAux checked checked.type.ctors 0

/-- Public motive generation is the identity-normalization specialization of
the mixed raw/view implementation. -/
def motiveType {decl : VInductDecl} (checked : decl.Checked) : VExpr :=
  checked.identityGeneration.motiveType

/-- Public minor generation is the identity-normalization specialization of
the mixed raw/view implementation. -/
def minorTypes {decl : VInductDecl} (checked : decl.Checked) : List VExpr :=
  checked.identityGeneration.minorTypes

/-- Public recursor generation is the identity-normalization specialization
of the mixed raw/view implementation. -/
def recursor {decl : VInductDecl} (checked : decl.Checked) : VConstant :=
  checked.identityGeneration.recursor

/-- Public iota-rule generation is the identity-normalization specialization
of the mixed raw/view implementation. -/
def generatedRules {decl : VInductDecl} (checked : decl.Checked) : List VDefEq :=
  checked.identityGeneration.generatedRules

/-- The public motive retains the exact legacy identity-normal form. -/
theorem motiveType_eq_legacy {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.motiveType =
      VInductDecl.motiveType decl.uvars checked.type.name decl.nparams
        checked.type :=
  identity_motiveType checked

/-- The public minor telescope retains the exact legacy identity-normal
form, including functional recursive arguments. -/
theorem minorTypes_eq_legacy {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.minorTypes =
      VInductDecl.minorTypesRec decl.uvars checked.type.name decl.nparams
        checked.type checked.type.ctors :=
  identity_minorTypes checked

/-- The public recursor retains the exact legacy identity-normal form while
being generated by the mixed implementation. -/
theorem recursor_eq_legacy {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.recursor =
      VInductDecl.recConstRec decl.uvars checked.type.name decl.nparams
        checked.type :=
  identity_recursor checked

/-- The public iota-rule list retains the exact legacy identity-normal form
while being generated by the mixed implementation. -/
theorem generatedRules_eq_legacy {decl : VInductDecl}
    (checked : decl.Checked) :
    checked.generatedRules =
      VInductDecl.rulesRec decl.uvars checked.type.name decl.nparams
        checked.type :=
  identity_generatedRules checked

end Checked

/-- Semantic evidence for a recursive argument beneath a Pi telescope. The
binder domains are checked over the constructor context before the recursive
field; its terminal index spine is checked underneath those binders. -/
def RecArg.WF (r : RecArg) (env : VEnv) (l : VLevel) (Is : List VExpr)
    (Γ : List VExpr) : Prop :=
  VEnv.OnTel env U Γ r.binders ∧
  env.SpineWF U (r.binders.reverse ++ Γ)
    (VExpr.forallN (VExpr.liftTelN (r.fieldIndex + r.binders.length) Is 0)
      (.sort l))
    r.indices (.sort l)

/-- Semantic well-formedness of constructor fields over the pre-environment.
Direct recursive fields retain the Stage-3 spine contract. A recursive Pi
field additionally carries a well-formed binder telescope and the terminal
index spine below it. Non-recursive fields are well-formed types; non-Prop
families retain the universe bound, while Prop uses Lean's impredicative
exception. -/
def fieldsWF (env : VEnv) (l : VLevel) (Is : List VExpr) :
    List VExpr → Nat → List VExpr → Prop
  | _, _, [] => True
  | Γ, j, B :: Bs =>
    (isRecField U T np Is.length j B = true ∨
      (∃ r, recArg? U T np Is.length j B = some r ∧ r.binders ≠ [] ∧
        r.WF U env l Is Γ) ∨
      recArg? U T np Is.length j B = none ∧
        ∃ u, env.HasType U Γ B (.sort u) ∧ (l = .zero ∨ u ≤ l)) ∧
    (isRecField U T np Is.length j B = true →
      env.SpineWF U Γ (VExpr.forallN (VExpr.liftTelN j Is 0) (.sort l))
        (recFieldIdxs np B) (.sort l)) ∧
    fieldsWF env l Is (B :: Γ) (j+1) Bs

/-- Environment-indexed semantic evidence for a successful structural
analysis. This is the one-family counterpart of the kernel's `checkType` and
constructor checking passes: `Checked` owns normalized syntax, while
`Checked.WF` proves that syntax meaningful over the input environment. -/
def Checked.WF {decl : VInductDecl} (checked : decl.Checked) (env : VEnv) : Prop :=
  VEnv.OnTel env decl.uvars [] (checked.params ++ checked.indices) ∧
  ∀ c ∈ checked.type.ctors,
    fieldsWF decl.uvars checked.type.name decl.nparams env checked.resultLevel
      checked.indices checked.params.reverse 0
      (ctorFields (VExpr.dropN decl.nparams c.type)) ∧
    env.SpineWF decl.uvars
      ((ctorFields (VExpr.dropN decl.nparams c.type)).reverse ++ checked.params.reverse)
      (VExpr.forallN
        (VExpr.liftTelN (ctorFields (VExpr.dropN decl.nparams c.type)).length
          checked.indices 0)
        (.sort checked.resultLevel))
      (recFieldIdxs decl.nparams (VExpr.resultOf (VExpr.dropN decl.nparams c.type)))
      (.sort checked.resultLevel)

/-- Semantic certificate for an accepted raw/view pair. The normalization
justifies the raw metadata against the view, while `Checked.WF` justifies the
view's analyzer facts in the same input Theory environment. -/
def NormalizedChecked.WF {source : VInductDecl}
    (block : NormalizedChecked source) (env : VEnv) : Prop :=
  block.normalization.WF env ∧ block.checked.WF env

/-- The binders emitted for one mixed minor/rule: the checked family
parameters followed by the stored raw constructor fields.

Lean consumes parameter annotations while checking the family and uses those
checked locals when it builds the recursor. Constructor fields, by contrast,
retain their stored surface syntax. -/
def NormalizedCtor.emittedBinders {source : VInductDecl}
    (block : NormalizedChecked source) (ctor : NormalizedCtor) : List VExpr :=
  block.checked.params ++ ctor.rawFields source.nparams

/-- The normalized binders whose semantic analysis drives the mixed artifact.
These expressions are never emitted in place of their raw partners. -/
def NormalizedCtor.viewBinders {source : VInductDecl}
    (block : NormalizedChecked source) (ctor : NormalizedCtor) : List VExpr :=
  block.checked.params ++ ctor.view.fields

/-- The normalized constructor result reconstructed with the retained raw
family identity. It is interpreted in either of the raw contexts certified
below. -/
def NormalizedCtor.resultTarget {source : VInductDecl}
    (block : NormalizedChecked source) (ctor : NormalizedCtor) : VExpr :=
  VExpr.appN (.const block.sourceType.name (VLevel.params source.uvars))
    (VExpr.bvarRevRange (ctor.rawFields source.nparams).length source.nparams ++
      ctor.view.resultIndices)

/-- Staged semantic evidence for one raw/view constructor pair.

`declaredTel`/`declaredResult` validate the exact stored constructor type so it
can be inserted. `emittedTel`/`emittedResult` validate the binder context used
by mixed minors and rules. The two raw parameter prefixes may be merely
definitionally equal; recording both paths therefore anticipates the kernel's
constructor-parameter behavior without assuming syntactic equality. -/
structure NormalizedCtor.WF {source : VInductDecl}
    (block : NormalizedChecked source) (ctor : NormalizedCtor)
    (env : VEnv) : Prop where
  declaredTel :
    env.TelDefEq source.uvars []
      (ctor.declaredBinders source.nparams) (ctor.viewBinders block)
  declaredResult :
    env.IsDefEq source.uvars (ctor.declaredBinders source.nparams).reverse
      (ctor.rawResult source.nparams) (ctor.resultTarget block)
      (.sort block.checked.resultLevel)
  emittedTel :
    env.TelDefEq source.uvars []
      (ctor.emittedBinders block) (ctor.viewBinders block)
  emittedResult :
    env.IsDefEq source.uvars (ctor.emittedBinders block).reverse
      (ctor.rawResult source.nparams) (ctor.resultTarget block)
      (.sort block.checked.resultLevel)

/-- Semantic certificate for a generation-ready raw/view block.

The family telescope/result are certified before family insertion.
Constructor certificates are quantified over the exact environment produced
by inserting the raw family constant. This staging is essential for aliases
whose constructor fields mention that family. No field of this structure is a
normalization oracle: every equality is an ordinary Theory derivation. -/
structure GenerationChecked.WF {source : VInductDecl}
    (gen : GenerationChecked source) (env : VEnv) : Prop where
  blockWF : gen.block.WF env
  familyTel :
    env.TelDefEq source.uvars []
      (gen.block.rawParams ++ gen.block.rawIndices)
      (gen.block.checked.params ++ gen.block.checked.indices)
  familyResult :
    env.IsDefEq source.uvars
      (gen.block.rawParams ++ gen.block.rawIndices).reverse
      gen.block.rawResult (.sort gen.block.checked.resultLevel)
      (.sort (.succ gen.block.checked.resultLevel))
  ctors :
    ∀ envT, env.addConst gen.block.sourceType.name
        gen.block.sourceType.toVConstant = some envT →
      ∀ ctor ∈ gen.block.ctorPairs, ctor.WF gen.block envT

/-- Consumer-facing semantic package for one generation-ready inductive
declaration.  The executable transaction inspects only `generation`; `wf` is
the ordinary Theory certificate used by preservation and is never a
normalization oracle.

Verify can erase checker-specific candidate provenance to this boundary
before handing a normalized transaction to downstream consumers. -/
structure GenerationCertificate (source : VInductDecl) (env : VEnv) where
  generation : GenerationChecked source
  wf : generation.WF env

end VInductDecl

def VInductDecl.WF (env : VEnv) (decl : VInductDecl) : Prop :=
  decl.stage3 ∧
  ∀ ty ∈ decl.types,
    VEnv.OnTel env decl.uvars []
      (VExpr.telN decl.nparams ty.type ++
        VInductDecl.ctorFields (VExpr.dropN decl.nparams ty.type)) ∧
    ∀ c ∈ ty.ctors,
      VInductDecl.fieldsWF decl.uvars ty.name decl.nparams env
        (VInductDecl.sortLevel decl.nparams ty)
        (VInductDecl.ctorFields (VExpr.dropN decl.nparams ty.type))
        (VExpr.telN decl.nparams ty.type).reverse 0
        (VInductDecl.ctorFields (VExpr.dropN decl.nparams c.type)) ∧
      env.SpineWF decl.uvars
        ((VInductDecl.ctorFields (VExpr.dropN decl.nparams c.type)).reverse ++
          (VExpr.telN decl.nparams ty.type).reverse)
        (VExpr.forallN
          (VExpr.liftTelN (VInductDecl.ctorFields (VExpr.dropN decl.nparams c.type)).length
            (VInductDecl.ctorFields (VExpr.dropN decl.nparams ty.type)) 0)
          (.sort (VInductDecl.sortLevel decl.nparams ty)))
        (VInductDecl.recFieldIdxs decl.nparams
          (VExpr.resultOf (VExpr.dropN decl.nparams c.type)))
        (.sort (VInductDecl.sortLevel decl.nparams ty))

/-- The single computational transaction for a generation-ready raw/view
block. Stored family and constructor constants come from the raw source;
recursor and rules come from the mixed artifact implementation. Semantic
validity is a theorem premise, never an input to this computation. -/
def VEnv.addInductGeneration {source : VInductDecl}
    (env : VEnv) (gen : source.GenerationChecked) : Option VEnv := do
  let ty := gen.block.sourceType
  let env ← env.addConst ty.name ty.toVConstant
  let env ← ty.ctors.foldlM
    (fun env c => env.addConst c.name c.toVConstant) env
  let env ← env.addConst (.str ty.name "rec") gen.recursor
  return gen.generatedRules.foldl VEnv.addDefEq env

/-- Public proof-carrying wrapper around `addInductGeneration`.

The certificate's proof is erased and does not influence computation.  This
entry point lets a verified producer expose a non-identity normalization
without exposing its checker trace or asking a consumer to remember a
separate preservation premise. -/
def VEnv.addInductCertified {source : VInductDecl}
    (env : VEnv) (certificate : source.GenerationCertificate env) :
    Option VEnv :=
  env.addInductGeneration certificate.generation

@[simp] theorem VEnv.addInductCertified_eq_addInductGeneration
    {source : VInductDecl} (env : VEnv)
    (certificate : source.GenerationCertificate env) :
    env.addInductCertified certificate =
      env.addInductGeneration certificate.generation :=
  rfl

/-- Exact intermediate states of a successful normalized inductive
transaction. Stable lookup, freshness, monotonicity, and preservation
consequences are derived from this one trace in the typing layer. -/
structure VEnv.AddInductGenerationTrace {source : VInductDecl}
    (env env' : VEnv) (gen : source.GenerationChecked) where
  typeEnv : VEnv
  ctorEnv : VEnv
  recEnv : VEnv
  addType :
    env.addConst gen.block.sourceType.name
      gen.block.sourceType.toVConstant = some typeEnv
  addCtors :
    gen.block.sourceType.ctors.foldlM
      (fun env c => env.addConst c.name c.toVConstant) typeEnv =
        some ctorEnv
  addRec :
    ctorEnv.addConst (.str gen.block.sourceType.name "rec")
      gen.recursor = some recEnv
  addRules :
    gen.generatedRules.foldl VEnv.addDefEq recEnv = env'

/-- The existing raw-normal-form API is exactly the identity-normalization
wrapper around `addInductGeneration`. -/
def VEnv.addInduct (env : VEnv) (decl : VInductDecl) : Option VEnv := do
  let checked ← decl.checked?
  env.addInductGeneration checked.identityGeneration

/-- The raw public API is transparently the identity-normalization
specialization of the normalized transaction. -/
theorem VEnv.addInduct_eq_addInductGeneration
    (env : VEnv) (decl : VInductDecl) :
    env.addInduct decl =
      decl.checked? >>= fun checked =>
        env.addInductGeneration checked.identityGeneration :=
  rfl

/-- Stable, consumer-facing consequences of a successful `addInduct`
transaction. This deliberately hides the internal `foldlM` sequence: a
caller receives the complete output environment and all generated objects, or
`addInduct` returns `none` without exposing an intermediate environment. -/
structure VEnv.AddInductSuccess (env env' : VEnv) (decl : VInductDecl) : Prop where
  checked : ∃ checked, decl.checked? = some checked
  accepted : decl.stage3 = true
  singleton : ∃ ty, decl.types = [ty]
  le : env ≤ env'
  type_fresh : ∀ ty ∈ decl.types, env.constants ty.name = none
  type_lookup : ∀ ty ∈ decl.types, env'.constants ty.name = some ty.toVConstant
  ctor_fresh : ∀ ty ∈ decl.types, ∀ c ∈ ty.ctors, env.constants c.name = none
  ctor_lookup : ∀ ty ∈ decl.types, ∀ c ∈ ty.ctors,
    env'.constants c.name = some c.toVConstant
  rec_fresh : ∀ ty ∈ decl.types, env.constants (.str ty.name "rec") = none
  rec_lookup : ∀ ty ∈ decl.types,
    env'.constants (.str ty.name "rec") =
      some (VInductDecl.recConstRec decl.uvars ty.name decl.nparams ty)
  rule_mem : ∀ ty ∈ decl.types,
    ∀ df ∈ VInductDecl.rulesRec decl.uvars ty.name decl.nparams ty, env'.defeqs df
