import Lean4Lean.Theory.Inductive
import Lean4Lean.Theory.Typing.Strong

/-! # Theory encodings of Lean literals and primitive reflection

This file contains only `VExpr`/`VEnv` semantics.  Traversal of `Lean.Expr`
and `Literal.toConstructor` belongs to the Verify translation layer.
-/

namespace Lean4Lean
open Lean

def VEnv.ContainsLits (env : VEnv) : Literal → Prop
  | .natVal _ => env.contains ``Nat
  | .strVal _ => env.contains ``Char.ofNat ∧ env.contains ``String.ofList

def VExpr.bool : VExpr := .const ``Bool []
def VExpr.boolTrue : VExpr := .const ``Bool.true []
def VExpr.boolFalse : VExpr := .const ``Bool.false []
def VExpr.boolLit : Bool → VExpr
  | .false => .boolFalse
  | .true => .boolTrue

def VExpr.nat : VExpr := .const ``Nat []
def VExpr.natZero : VExpr := .const ``Nat.zero []
def VExpr.natSucc : VExpr := .const ``Nat.succ []
def VExpr.natLit : Nat → VExpr
  | 0 => .natZero
  | n+1 => .app .natSucc (.natLit n)

def VExpr.char : VExpr := .const ``Char []
def VExpr.string : VExpr := .const ``String []
def VExpr.stringOfList : VExpr := .const ``String.ofList []
def VExpr.listChar : VExpr := .app (.const ``List [.zero]) .char
def VExpr.listCharNil : VExpr := .app (.const ``List.nil [.zero]) .char
def VExpr.listCharCons : VExpr := .app (.const ``List.cons [.zero]) .char
def VExpr.charOfNat : VExpr := .const ``Char.ofNat []
def VExpr.listCharLit : List Char → VExpr
  | [] => .listCharNil
  | a :: as =>
    .app (.app .listCharCons (.app .charOfNat (.natLit a.toNat))) (.listCharLit as)

def VExpr.trLiteral : Literal → VExpr
  | .natVal n => .natLit n
  | .strVal s => .app .stringOfList (.listCharLit s.toList)

def VExpr.literalType : Literal → VExpr
  | .natVal _ => .nat
  | .strVal _ => .string

/-! ## Exact prelude artifacts

`ContainsLits` deliberately records only name occurrence.  The declarations
below describe the exact Theory artifacts that make those names meaningful.
The inductive recursors and iota rules are generated by the same
consumer-neutral Theory machinery used by `VEnv.addInduct`.
-/

namespace LiteralPrelude

def boolFalse : VConstVal :=
  { name := ``Bool.false, uvars := 0, type := .bool }

def boolTrue : VConstVal :=
  { name := ``Bool.true, uvars := 0, type := .bool }

def boolType : VInductiveType where
  name := ``Bool
  uvars := 0
  type := .sort (.succ .zero)
  ctors := [boolFalse, boolTrue]

def boolRec : VConstant := VInductDecl.recConst 0 ``Bool 0 boolType
def boolIotas : List VDefEq := VInductDecl.rules 0 ``Bool 0 boolType

def natZero : VConstVal :=
  { name := ``Nat.zero, uvars := 0, type := .nat }

def natSucc : VConstVal :=
  { name := ``Nat.succ, uvars := 0, type := .forallE .nat .nat }

def natType : VInductiveType where
  name := ``Nat
  uvars := 0
  type := .sort (.succ .zero)
  ctors := [natZero, natSucc]

def natRec : VConstant := VInductDecl.recConst 0 ``Nat 0 natType
def natIotas : List VDefEq := VInductDecl.rules 0 ``Nat 0 natType

def char : VConstant := { uvars := 0, type := .sort (.succ .zero) }
def charOfNat : VConstant := { uvars := 0, type := .forallE .nat .char }

def listNil : VConstVal where
  name := ``List.nil
  uvars := 1
  type := .forallE (.sort (.succ (.param 0)))
    (.app (.const ``List [.param 0]) (.bvar 0))

def listCons : VConstVal where
  name := ``List.cons
  uvars := 1
  type := .forallE (.sort (.succ (.param 0))) <|
    .forallE (.bvar 0) <|
      .forallE (.app (.const ``List [.param 0]) (.bvar 1))
        (.app (.const ``List [.param 0]) (.bvar 2))

def listType : VInductiveType where
  name := ``List
  uvars := 1
  type := .forallE (.sort (.succ (.param 0))) (.sort (.succ (.param 0)))
  ctors := [listNil, listCons]

def listRec : VConstant := VInductDecl.recConst 1 ``List 1 listType
def listIotas : List VDefEq := VInductDecl.rules 1 ``List 1 listType

def string : VConstant := { uvars := 0, type := .sort (.succ .zero) }
def stringOfList : VConstant :=
  { uvars := 0, type := .forallE .listChar .string }

end LiteralPrelude

/-- The exact kernel-facing prelude fragment needed to interpret Theory
literals.  In contrast with `ContainsLits`, this records declaration types,
recursors, iota rules, and an ordered construction history. -/
structure VEnv.PreludeReady (env : VEnv) : Prop where
  ordered : env.Ordered
  bool : env.constants ``Bool = some LiteralPrelude.boolType.toVConstant
  boolFalse : env.constants ``Bool.false =
    some LiteralPrelude.boolFalse.toVConstant
  boolTrue : env.constants ``Bool.true =
    some LiteralPrelude.boolTrue.toVConstant
  boolRec : env.constants ``Bool.rec = some LiteralPrelude.boolRec
  boolIotas : ∀ df ∈ LiteralPrelude.boolIotas, env.defeqs df
  nat : env.constants ``Nat = some LiteralPrelude.natType.toVConstant
  natZero : env.constants ``Nat.zero =
    some LiteralPrelude.natZero.toVConstant
  natSucc : env.constants ``Nat.succ =
    some LiteralPrelude.natSucc.toVConstant
  natRec : env.constants ``Nat.rec = some LiteralPrelude.natRec
  natIotas : ∀ df ∈ LiteralPrelude.natIotas, env.defeqs df
  char : env.constants ``Char = some LiteralPrelude.char
  charOfNat : env.constants ``Char.ofNat = some LiteralPrelude.charOfNat
  list : env.constants ``List = some LiteralPrelude.listType.toVConstant
  listNil : env.constants ``List.nil =
    some LiteralPrelude.listNil.toVConstant
  listCons : env.constants ``List.cons =
    some LiteralPrelude.listCons.toVConstant
  listRec : env.constants ``List.rec = some LiteralPrelude.listRec
  listIotas : ∀ df ∈ LiteralPrelude.listIotas, env.defeqs df
  string : env.constants ``String = some LiteralPrelude.string
  stringOfList : env.constants ``String.ofList = some LiteralPrelude.stringOfList

namespace VEnv.PreludeReady

/-- Exact prelude artifacts transport across environment inclusion.  The
target ordering premise is necessary because arbitrary `VEnv.LE` growth may
append an ill-typed declaration. -/
theorem mono {env env' : VEnv} (H : env.PreludeReady) (henv : env ≤ env')
    (hordered : env'.Ordered) : env'.PreludeReady where
  ordered := hordered
  bool := henv.constants H.bool
  boolFalse := henv.constants H.boolFalse
  boolTrue := henv.constants H.boolTrue
  boolRec := henv.constants H.boolRec
  boolIotas := fun df hdf => henv.defeqs (H.boolIotas df hdf)
  nat := henv.constants H.nat
  natZero := henv.constants H.natZero
  natSucc := henv.constants H.natSucc
  natRec := henv.constants H.natRec
  natIotas := fun df hdf => henv.defeqs (H.natIotas df hdf)
  char := henv.constants H.char
  charOfNat := henv.constants H.charOfNat
  list := henv.constants H.list
  listNil := henv.constants H.listNil
  listCons := henv.constants H.listCons
  listRec := henv.constants H.listRec
  listIotas := fun df hdf => henv.defeqs (H.listIotas df hdf)
  string := henv.constants H.string
  stringOfList := henv.constants H.stringOfList

/-- Any successful well-formed constant insertion preserves readiness.  It is
necessarily unrelated to the ready prelude: all of those names are already
occupied, while `addConst` succeeds only at a fresh name. -/
theorem addConst {env env' : VEnv} (H : env.PreludeReady)
    (hci : ci.WF env) (hadd : env.addConst name ci = some env') :
    env'.PreludeReady :=
  H.mono (VEnv.addConst_le hadd) (.const H.ordered hci hadd)

/-- Adding a well-formed unrelated definitional equation preserves prelude
readiness. -/
theorem addDefEq {env : VEnv} (H : env.PreludeReady) (hdf : df.WF env) :
    (env.addDefEq df).PreludeReady :=
  H.mono VEnv.addDefEq_le (.defeq H.ordered hdf)

/-- A ready prelude contains every name used by the direct literal encoding. -/
theorem containsLits {env : VEnv} (H : env.PreludeReady) :
    ∀ l, env.ContainsLits l
  | .natVal _ => ⟨_, H.nat⟩
  | .strVal _ => ⟨⟨_, H.charOfNat⟩, ⟨_, H.stringOfList⟩⟩

end VEnv.PreludeReady

def VEnv.ReflectsNatNatNat (env : VEnv) (fc : Name) (f : Nat → Nat → Nat) :=
  env.contains fc →
  ∀ a b, env.IsDefEqU 0 []
    (.app (.app (.const fc []) (.natLit a)) (.natLit b)) (.natLit (f a b))

def VEnv.ReflectsNatNatBool (env : VEnv) (fc : Name) (f : Nat → Nat → Bool) :=
  env.contains fc →
  ∀ a b, env.IsDefEqU 0 []
    (.app (.app (.const fc []) (.natLit a)) (.natLit b)) (.boolLit (f a b))

structure VEnv.HasPrimitives (env : VEnv) : Prop where
  bool : env.contains ``Bool → env.contains ``Bool.false ∧ env.contains ``Bool.true
  boolFalse : env.constants ``Bool.false = some ci → ci = { uvars := 0, type := .bool }
  boolTrue : env.constants ``Bool.true = some ci → ci = { uvars := 0, type := .bool }
  nat : env.contains ``Nat → env.contains ``Nat.zero ∧ env.contains ``Nat.succ
  natZero : env.constants ``Nat.zero = some ci → ci = { uvars := 0, type := .nat }
  natSucc : env.constants ``Nat.succ = some ci →
    ci = { uvars := 0, type := .forallE .nat .nat }
  natAdd : env.ReflectsNatNatNat ``Nat.add Nat.add
  natSub : env.ReflectsNatNatNat ``Nat.sub Nat.sub
  natMul : env.ReflectsNatNatNat ``Nat.mul Nat.mul
  natPow : env.ReflectsNatNatNat ``Nat.pow Nat.pow
  natGcd : env.ReflectsNatNatNat ``Nat.gcd Nat.gcd
  natMod : env.ReflectsNatNatNat ``Nat.mod Nat.mod
  natDiv : env.ReflectsNatNatNat ``Nat.div Nat.div
  natBEq : env.ReflectsNatNatBool ``Nat.beq Nat.beq
  natBLE : env.ReflectsNatNatBool ``Nat.ble Nat.ble
  natLAnd : env.ReflectsNatNatNat ``Nat.land Nat.land
  natLOr : env.ReflectsNatNatNat ``Nat.lor Nat.lor
  natXor : env.ReflectsNatNatNat ``Nat.xor Nat.xor
  natShiftLeft : env.ReflectsNatNatNat ``Nat.shiftLeft Nat.shiftLeft
  natShiftRight : env.ReflectsNatNatNat ``Nat.shiftRight Nat.shiftRight
  charOfNat : env.constants ``Char.ofNat = some ci →
    ci = { uvars := 0, type := .forallE .nat .char }
  stringOfList : env.constants ``String.ofList = some ci →
    ci = { uvars := 0, type := .forallE .listChar .string } ∧
    env.HasType 0 [] .listCharNil .listChar ∧
    env.HasType 0 [] .listCharCons (.forallE .char <| .forallE .listChar .listChar)

variable! {env env' : VEnv} (henv : env ≤ env') in
theorem VEnv.ContainsLits.mono : ∀ {l}, env.ContainsLits l → env'.ContainsLits l
  | .natVal _, ⟨_, H⟩ => ⟨_, henv.constants H⟩
  | .strVal _, ⟨⟨_, H1⟩, ⟨_, H2⟩⟩ =>
    ⟨⟨_, henv.constants H1⟩, ⟨_, henv.constants H2⟩⟩

namespace VEnv.PreludeReady

theorem boolFalse_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Bool.false = some { uvars := 0, type := VExpr.bool } := by
  simpa [LiteralPrelude.boolFalse] using H.boolFalse

theorem boolTrue_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Bool.true = some { uvars := 0, type := VExpr.bool } := by
  simpa [LiteralPrelude.boolTrue] using H.boolTrue

theorem natZero_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Nat.zero = some { uvars := 0, type := VExpr.nat } := by
  simpa [LiteralPrelude.natZero] using H.natZero

theorem natSucc_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Nat.succ =
      some { uvars := 0, type := VExpr.forallE .nat .nat } := by
  simpa [LiteralPrelude.natSucc] using H.natSucc

theorem char_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Char =
      some { uvars := 0, type := VExpr.sort (.succ .zero) } := by
  simpa [LiteralPrelude.char] using H.char

theorem charOfNat_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``Char.ofNat =
      some { uvars := 0, type := VExpr.forallE .nat .char } := by
  simpa [LiteralPrelude.charOfNat] using H.charOfNat

theorem stringOfList_lookup {env : VEnv} (H : env.PreludeReady) :
    env.constants ``String.ofList =
      some { uvars := 0, type := VExpr.forallE .listChar .string } := by
  simpa [LiteralPrelude.stringOfList] using H.stringOfList

theorem boolLit_hasType {env : VEnv} (H : env.PreludeReady) (b : Bool) :
    env.HasType U Γ (.boolLit b) .bool := by
  cases b
  · exact .const H.boolFalse_lookup nofun rfl
  · exact .const H.boolTrue_lookup nofun rfl

theorem natLit_hasType {env : VEnv} (H : env.PreludeReady) (n : Nat) :
    env.HasType U Γ (.natLit n) .nat := by
  induction n with
  | zero => exact .const H.natZero_lookup nofun rfl
  | succ n ih =>
    simpa [VExpr.natLit, VExpr.natSucc, VExpr.nat, VExpr.instL, VExpr.inst] using
      VEnv.HasType.app
        (VEnv.HasType.const (ls := []) H.natSucc_lookup (by simp) rfl) ih

theorem charOfNat_hasType {env : VEnv} (H : env.PreludeReady) :
    env.HasType U Γ .charOfNat (.forallE .nat .char) :=
  .const H.charOfNat_lookup nofun rfl

theorem listCharNil_hasType {env : VEnv} (H : env.PreludeReady) :
    env.HasType U Γ .listCharNil .listChar := by
  have hnil : env.constants ``List.nil = some {
      uvars := 1
      type := VExpr.forallE (.sort (.succ (.param 0)))
        (.app (.const ``List [.param 0]) (.bvar 0)) } := by
    simpa [LiteralPrelude.listNil] using H.listNil
  exact .app (.const hnil (by simp [VLevel.WF]) rfl)
    (.const H.char_lookup nofun rfl)

theorem listCharCons_hasType {env : VEnv} (H : env.PreludeReady) :
    env.HasType U Γ .listCharCons
      (.forallE .char <| .forallE .listChar .listChar) := by
  have hcons : env.constants ``List.cons = some {
      uvars := 1
      type := VExpr.forallE (.sort (.succ (.param 0))) <|
        .forallE (.bvar 0) <|
          .forallE (.app (.const ``List [.param 0]) (.bvar 1))
            (.app (.const ``List [.param 0]) (.bvar 2)) } := by
    simpa [LiteralPrelude.listCons] using H.listCons
  exact .app (.const hcons (by simp [VLevel.WF]) rfl)
    (.const H.char_lookup nofun rfl)

theorem listCharLit_hasType {env : VEnv} (H : env.PreludeReady)
    (cs : List Char) : env.HasType U Γ (.listCharLit cs) .listChar := by
  induction cs with
  | nil => exact H.listCharNil_hasType
  | cons c cs ih =>
    exact (H.listCharCons_hasType.app
      (H.charOfNat_hasType.app (H.natLit_hasType c.toNat))).app ih

theorem trLiteral_hasType {env : VEnv} (H : env.PreludeReady) (l : Literal) :
    env.HasType U Γ (.trLiteral l) (.literalType l) := by
  cases l with
  | natVal n => simpa [VExpr.trLiteral, VExpr.literalType] using H.natLit_hasType n
  | strVal s =>
    simpa [VExpr.trLiteral, VExpr.literalType, VExpr.stringOfList, VExpr.string,
      VExpr.instL, VExpr.inst] using
      VEnv.HasType.app
        (VEnv.HasType.const (ls := []) H.stringOfList_lookup (by simp) rfl)
        (H.listCharLit_hasType s.toList)

/-- Exact readiness, not name occurrence alone, makes a direct literal
encoding well-formed.  Pattern matching the containment witness ensures the
literal-facing premise is checked against the exact ready lookup. -/
theorem trLiteral_wf {env : VEnv} (H : env.PreludeReady) (l : Literal)
    (hcontains : env.ContainsLits l) :
    VExpr.WF env U [] (.trLiteral l) := by
  cases l with
  | natVal n =>
    obtain ⟨ci, hci⟩ := hcontains
    have : ci = LiteralPrelude.natType.toVConstant := by
      exact (Option.some.inj (H.nat.symm.trans hci)).symm
    subst ci
    exact ⟨_, H.trLiteral_hasType (.natVal n)⟩
  | strVal s =>
    obtain ⟨⟨charOfNat, hcharOfNat⟩, ⟨stringOfList, hstringOfList⟩⟩ := hcontains
    have : charOfNat = LiteralPrelude.charOfNat := by
      exact (Option.some.inj (H.charOfNat.symm.trans hcharOfNat)).symm
    subst charOfNat
    have : stringOfList = LiteralPrelude.stringOfList := by
      exact (Option.some.inj (H.stringOfList.symm.trans hstringOfList)).symm
    subst stringOfList
    exact ⟨_, H.trLiteral_hasType (.strVal s)⟩

end VEnv.PreludeReady

@[simp] theorem VExpr.instL_boolFalse : VExpr.boolFalse.instL ls = VExpr.boolFalse := by
  simp [boolFalse, instL]

@[simp] theorem VExpr.instL_boolTrue : VExpr.boolTrue.instL ls = VExpr.boolTrue := by
  simp [boolTrue, instL]

@[simp] theorem VExpr.instL_boolLit : (VExpr.boolLit b).instL ls = VExpr.boolLit b := by
  cases b <;> simp [boolLit]

@[simp] theorem VExpr.liftN_boolLit : (VExpr.boolLit b).liftN n k = VExpr.boolLit b := by
  cases b <;> rfl

@[simp] theorem VExpr.lift'_boolLit : (VExpr.boolLit b).lift' ρ = VExpr.boolLit b := by
  cases b <;> rfl

@[simp] theorem VExpr.inst_boolLit : (VExpr.boolLit b).inst e k = VExpr.boolLit b := by
  cases b <;> rfl

@[simp] theorem VExpr.instL_natZero : VExpr.natZero.instL ls = .natZero := by
  simp [natZero, instL]

@[simp] theorem VExpr.instL_natSucc : VExpr.natSucc.instL ls = .natSucc := by
  simp [natSucc, instL]

@[simp] theorem VExpr.instL_natLit : (VExpr.natLit n).instL ls = VExpr.natLit n := by
  induction n <;> simp [*, natLit, instL]

@[simp] theorem VExpr.liftN_natLit : (VExpr.natLit a).liftN n k = VExpr.natLit a := by
  induction a <;> simp [natLit, natZero, natSucc, VExpr.liftN, *]

@[simp] theorem VExpr.lift'_natLit : (VExpr.natLit a).lift' ρ = VExpr.natLit a := by
  induction a <;> simp [natLit, natZero, natSucc, VExpr.lift', *]

@[simp] theorem VExpr.inst_natLit : (VExpr.natLit a).inst e k = VExpr.natLit a := by
  induction a <;> simp [natLit, natZero, natSucc, VExpr.inst, *]

@[simp] theorem VExpr.liftN_listCharLit :
    (VExpr.listCharLit cs).liftN n k = VExpr.listCharLit cs := by
  induction cs <;>
    simp [listCharLit, listCharNil, listCharCons, char, charOfNat, VExpr.liftN, *]

@[simp] theorem VExpr.lift'_listCharLit :
    (VExpr.listCharLit cs).lift' ρ = VExpr.listCharLit cs := by
  induction cs <;>
    simp [listCharLit, listCharNil, listCharCons, char, charOfNat, VExpr.lift', *]

@[simp] theorem VExpr.inst_listCharLit :
    (VExpr.listCharLit cs).inst e k = VExpr.listCharLit cs := by
  induction cs <;>
    simp [listCharLit, listCharNil, listCharCons, char, charOfNat, VExpr.inst, *]

@[simp] theorem VExpr.instL_listCharLit :
    (VExpr.listCharLit cs).instL ls = VExpr.listCharLit cs := by
  induction cs <;>
    simp [listCharLit, listCharNil, listCharCons, char, charOfNat,
      VExpr.instL, VLevel.inst, *]

@[simp] theorem VExpr.liftN_trLiteral :
    (VExpr.trLiteral l).liftN n k = VExpr.trLiteral l := by
  cases l <;> simp [trLiteral, stringOfList, VExpr.liftN]

@[simp] theorem VExpr.lift'_trLiteral :
    (VExpr.trLiteral l).lift' ρ = VExpr.trLiteral l := by
  cases l <;> simp [trLiteral, stringOfList, VExpr.lift']

@[simp] theorem VExpr.inst_trLiteral :
    (VExpr.trLiteral l).inst e k = VExpr.trLiteral l := by
  cases l <;> simp [trLiteral, stringOfList, VExpr.inst]

@[simp] theorem VExpr.instL_trLiteral :
    (VExpr.trLiteral l).instL ls = VExpr.trLiteral l := by
  cases l <;> simp [trLiteral, stringOfList, VExpr.instL]

theorem VEnv.HasPrimitives.nat_of_charOfNat (wf : Ordered env)
    (henv : env.HasPrimitives) (H : env.contains ``Char.ofNat) : env.contains ``Nat := by
  let ⟨_, H⟩ := H
  have ⟨_, H⟩ := wf.constWF (henv.charOfNat H ▸ H)
  let ⟨⟨_, H⟩, _⟩ := H.forallE_inv wf
  let ⟨_, H, _⟩ := H.const_inv (Γ := []) wf (by trivial)
  exact ⟨_, H⟩

/--
info: 'Lean4Lean.VEnv.PreludeReady.mono' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms VEnv.PreludeReady.mono

/--
info: 'Lean4Lean.VEnv.PreludeReady.addConst' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms VEnv.PreludeReady.addConst

/--
info: 'Lean4Lean.VEnv.PreludeReady.addDefEq' depends on axioms: [propext, Quot.sound]
-/
#guard_msgs in
#print axioms VEnv.PreludeReady.addDefEq

/--
info: 'Lean4Lean.VEnv.PreludeReady.trLiteral_wf' depends on axioms: [propext, Classical.choice, Quot.sound]
-/
#guard_msgs in
#print axioms VEnv.PreludeReady.trLiteral_wf

end Lean4Lean
